### ISSUE TITLE
Functional Test bot does not respond

### ISSUE THREAD

**Issue by mrivera-ms** [microsoft/BotFramework-FunctionalTests#243]
## Describe the bug
**DotNet21JsSkillBotFunctionalTest** fails due to time out errors. 
`2021-01-20T13:22:40.7926957Z   Error Message:
2021-01-20T13:22:40.7927543Z    System.TimeoutException : operation timed out while waiting for a response from the bot
`

## To Reproduce
Run the host bot locally or deploy to Azure and test in WebChat.

**Comment by gabog** [comment]
Closing for now, I think this has been fixed in #245 which:

- Fixes timeouts that may occur when the bot takes a long time to start and DL client ends up in limbo.
- Fixes timeouts that may occur when DL sends messages back to the bot out of sequence (yes, this may happen ☹). 
- Fixes a bug in the timeout logic for GetNextReply in TestRunner.
- Uses websockets for DL instead of polling to avoid being too chatty.
- Adds a config setting for GetNextReply timeout and sets it to 180 seconds by default. Here we need to keep in mind that the dotnet hosts use HttpClient to talk to the skills and the default timeout for HttpClient is 100 seconds, so the GetNextReply should wait for longer than that.
- Adds a ton of LogDebug and LogTrace calls to DirectLineClient to help us understand any issues in the future.
